### PR TITLE
Fix #359 add missing api.php

### LINKED ISSUE #359: Missing api.php in the routes directory
- Themosis Version: master

### Description

When you create a new project on the current master branch, you will get the following error:

```bash
In RouteFileRegistrar.php line 35:

  require(/Users/rbackhau/Projects/themosis-bug/routes/api.php): Failed to op
  en stream: No such file or directory
```

### Steps to reproduce

`composer create-project themosis/themosis themosis-master "dev-master"`

### Expected behavior

I guess the master should add the current api.php from https://github.com/laravel/laravel/blob/8.x/routes/api.php to avoid this issue.

### PR DESCRIPTION
**Pull request by reneroboter**
@jlambe  in the following [commit](https://github.com/themosis/themosis/commit/1e023c528fef11af9f8ad85db14d0e15a7cf85e7) you add the default provider from Laravel so I added the default [api.php](https://github.com/laravel/laravel/blob/8.x/routes/api.php) to fix #359. Hopefully I did everything right :)

### CODE REVIEW

**Comment by jlambe** [comment]
Well this seems ok. I will verify a bit later on this. Thanks for your PR 😃

**Comment by charlesastwood** [comment]
Did this get merged into `main` as I am getting error `routes/api.php): Failed to open stream: No such file or directory ` when trying to install

**Comment by jlambe** [comment]
@charlesastwood It is still missing, apparently when I changed the branch name it closed the PR. You can add the file in your project directly.

**Comment by jlambe** [comment]
@reneroboter @charlesastwood This has been merged now. I lost track of this PR after renaming the default branch for the project. Thanks.

**Pull request closed without merging**
